# -*- coding: utf-8 -*-
"""Automação simples.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1024YgKW6FyoaVsc9vh010Caz2U12kHqM
"""

from selenium import webdriver
from time import sleep
import pyautogui
import time
import itertools


#PROCESSO INICIAL DE LOGIN EM PAG (SE NECESSÁRIO)!


driver = webdriver.Chrome() #neste caso se trata de uma automação com o chrome, mas é totalmente modular
driver.get(url=#'url básica de acesso - topo do navegador')
time.sleep(2) #time sleep é necessário para respeitar o tempo de carregamento das telas, alterável conforme projeto
search = driver.find_element_by_id("user")
search.send_keys(#'SEU USUÁRIO')
search = driver.find_element_by_id("password")
search.send_keys(#'SUA SENHA')

time.sleep(2) #time sleep é necessário para respeitar o tempo de carregamento das telas, alterável conforme projeto
search = driver.find_element_by_id("loginButton")
time.sleep(1) #time sleep é necessário para respeitar o tempo de carregamento das telas, alterável conforme projeto
pyautogui.press('enter')


#TAKS básicas considerando busca através de janela suspensa de pesquisa


time.sleep(2) 
driver.get(#url direcional - comumente encontrada como generic dentro dos elements com div especifica)
time.sleep(2)
search = driver.find_element_by_id(#botão generico referente ao campo de busca).click()
time.sleep(2)
pyautogui.write(#texto generico de busca para task')
pyautogui.press('enter')
pyautogui.press('tab')
pyautogui.press('enter')

#Mudar de janela para pegar determinado arquivo marcado em coordenada e arrastar arquivo para dentro do diretória - para achar a coordenada vc pode usar o pyautogui.position()

pyautogui.hotkey('winleft', 'd')
pyautogui.moveTo(2000, 155)
pyautogui.mouseDown()
pyautogui.moveTo(3000, 523)
pyautogui.hotkey('alt', 'tab')
time.sleep(2)
pyautogui.mouseUp()
time.sleep(2)

pyautogui.alert("O Código foi finalizado!")

#Bibliotca com mais recursos vc encontra no link a seguir:https://pyautogui.readthedocs.io/en/latest/quickstart.html)
